language: python
sudo: required

matrix:
  include:
    - dist: trusty
      env: dist="14.04 LTS trusty"
    #- dist: xenial  # very unstable.
    #  env: dist="16.04 LTS xenial"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ansible libffi-dev libssl-dev

# bare metal installation
install:
  - cd ansible; sudo ansible-playbook -i "localhost," -c local -v install_fogbed.yml; cd ..

# run tests
script:
  # run unit tests (bare metal)
  - sudo py.test -v mininet/test/test_containernet.py
  # build ubuntu-based docker container
  - docker build -t containernet/containernet:ubuntu .
  # build centos-based docker container
  #- docker build -t containernet/containernet:centos7 -f Dockerfile.centos .
  # run unit tests on ubuntu:xenial-based docker container
  - docker run --name containernet -i --rm --privileged --pid='host' -v /var/run/docker.sock:/var/run/docker.sock containernet/containernet:ubuntu  py.test -v mininet/test/test_containernet.py
  # run unit tests on centos7-based docker container
  #- docker run --name containernet -i --rm --privileged --pid='host' -v /var/run/docker.sock:/var/run/docker.sock containernet/containernet:centos7  py.test -v mininet/test/test_containernet.py

notifications:
  email:
    on_success: change
    on_failure: always
